# Base configs
baseurl: "https://luckygirlcai.github.io/images/"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by luckygirlcai"
subtitle: "See the world through my eyes!"
author: "Ram Patra"
header:
 title: "Photography"
 subtitle: "by luckygirlcai"
footer:
 name: "Hey there, my name is luckygirlcai"
 bio: "I'm a designer."
 github: "Want a website like this for yourself for free? Just <a href=\"https://github.com/luckygirlcai\">fork me on github</a> ;)"
web_design: "luckygirlcai"
social_urls:
  facebook: "https://www.facebook.com/ramswaroop"
  twitter: "https://www.twitter.com/ram__patra"
  instagram: "https://www.instagram.com/ram_patra"
  dribbble: "https://dribbble.com/rampatra"
  linkedin: "https://in.linkedin.com/in/ram-patra"
  github: "https://www.github.com/rampatra"
